type = "webpack"
name = "dailyheartsbot"
main = "src/index.js"
compatibility_date = "2024-02-24"

[triggers]
crons = [ "1 * * * *" ]

[env.production]
name = "production"
webpack_config = "webpack.config.js"